package domain

import (
	"encoding/base64"
	"errors"
	"fmt"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var testAlgorithms = map[string]Algorithm[KeyPair]{
	"Dummy": dummyAlgorithm{},
}

func TestGenerateSecureDataToBeSign(t *testing.T) {
	message := "this is the data"
	lastSignature := "last signature"
	lastSignatureBase64 := base64.StdEncoding.EncodeToString([]byte(lastSignature))
	deviceId, error := uuid.NewRandom()
	require.Nil(t, error)

	t.Run("Initial signature with counter 0", func(t *testing.T) {
		signatureCount := 0

		got := generateSecureDataToBeSign(signatureCount, message, lastSignatureBase64, deviceId)
		deviceIdBase64 := base64.StdEncoding.EncodeToString(deviceId[:])
		expect := fmt.Sprintf("%d_%s_%s", signatureCount, message, deviceIdBase64)
		assert.Equal(t, expect, got)
	})

	t.Run("Subsequent signature with counter > 0", func(t *testing.T) {
		signatureCount := 1

		got := generateSecureDataToBeSign(signatureCount, message, lastSignatureBase64, deviceId)
		expect := fmt.Sprintf("%d_%s_%s", signatureCount, message, lastSignatureBase64)
		assert.Equal(t, expect, got)
	})
}

type dummyAlgorithm struct{}

func (d dummyAlgorithm) CreateKeyPair() (KeyPair, error) {
	return "the key", nil
}

func (d dummyAlgorithm) SignData(data string, keyPair KeyPair) ([]byte, error) {
	if keyPair != "the key" {
		// TODO: handle this differently, either with a specific test or passing the testing.T
		return nil, errors.New("The key was not generated by this algorithm")
	}
	return []byte(data), nil
}

func TestNewSignatureService(t *testing.T) {
	t.Run("Empty algorithms", func(t *testing.T) {
		emptyAlgorithms := make(map[string]Algorithm[KeyPair])
		signatureService, err := NewSignatureService(emptyAlgorithms)
		assert.Nil(t, signatureService)
		assert.NotNil(t, err)
	})

	t.Run("With algorithms", func(t *testing.T) {
		signatureService, err := NewSignatureService(testAlgorithms)
		assert.Nil(t, err)
		assert.NotNil(t, signatureService)
	})
}

func TestNewSignatureDevice(t *testing.T) {
	t.Run("With inexisting algorithm", func(t *testing.T) {
		signatureService, err := NewSignatureService(testAlgorithms)
		require.Nil(t, err)
		_, err = signatureService.NewSignatureDevice("RSA", "first device")
		assert.EqualError(t, err, "algorithm RSA not in algorithms")
	})

	t.Run("With correct algorithm", func(t *testing.T) {
		signatureService, err := NewSignatureService(testAlgorithms)
		require.Nil(t, err)
		deviceId, err := signatureService.NewSignatureDevice("Dummy", "first device")
		assert.Nil(t, err)
		device, ok := signatureService.devices[deviceId]
		assert.True(t, ok)
		assert.Equal(t, 0, device.signatureCounter)
		assert.Equal(t, "", device.lastSignatureBase64)
	})
}

func TestSignatureServiceSign(t *testing.T) {
	t.Run("Sign data first time", func(t *testing.T) {
		signatureService, err := NewSignatureService(testAlgorithms)
		require.Nil(t, err)
		deviceId, err := signatureService.NewSignatureDevice("Dummy", "first device")
		require.Nil(t, err)
		message := "this is the data"
		signature, _, err := signatureService.SignData(deviceId, message)
		assert.Nil(t, err)
		deviceIdBase64 := base64.StdEncoding.EncodeToString(deviceId[:])
		specialString := fmt.Sprintf("%d_%s_%s", 0, message, deviceIdBase64)
		expect := base64.StdEncoding.EncodeToString([]byte(specialString))
		assert.Equal(t, expect, signature)
	})

	t.Run("Sign data", func(t *testing.T) {
		signatureService, err := NewSignatureService(testAlgorithms)
		require.Nil(t, err)
		deviceId, err := signatureService.NewSignatureDevice("Dummy", "first device")
		require.Nil(t, err)
		message := "this is the data"
		signature, _, err := signatureService.SignData(deviceId, message)
		require.Nil(t, err)
		newSignature, _, err := signatureService.SignData(deviceId, message)
		specialString := fmt.Sprintf("%d_%s_%s", 1, message, signature)
		expect := base64.StdEncoding.EncodeToString([]byte(specialString))
		assert.Equal(t, expect, newSignature)
	})
}

func TestListSignatureDevice(t *testing.T) {
	t.Run("Empty list", func(t *testing.T) {
		signatureService, err := NewSignatureService(testAlgorithms)
		require.Nil(t, err)
		devices := signatureService.GetDevices()
		assert.Len(t, devices, 0)
	})
	t.Run("Not empty list", func(t *testing.T) {
		signatureService, err := NewSignatureService(testAlgorithms)
		require.Nil(t, err)
		_, err = signatureService.NewSignatureDevice("Dummy", "first device")
		require.Nil(t, err)
		devices := signatureService.GetDevices()
		assert.Len(t, devices, 1)
	})
}
