package domain

import (
	"errors"
)

var testAlgorithms = map[string]Algorithm[KeyPair]{
	"Dummy": dummyAlgorithm{},
}

type dummyAlgorithm struct{}

func (d dummyAlgorithm) CreateKeyPair() (KeyPair, error) {
	return "the key", nil
}

func (d dummyAlgorithm) SignData(data string, keyPair KeyPair) ([]byte, error) {
	if keyPair != "the key" {
		return nil, errors.New("The key was not generated by this algorithm")
	}
	return []byte(data), nil
}

func (d dummyAlgorithm) Marshal(KeyPair KeyPair) ([]byte, []byte, error) {
	return []byte("public key"), []byte("private key"), nil
}

func (d dummyAlgorithm) Unmarshal(privateKeyBytes []byte) (KeyPair, error) {
	privateKey := string(privateKeyBytes)
	if privateKey != "private key" {
		return "", errors.New("Invalid key")
	}
	return "the key", nil
}
